== The Gateway Client

In our super secure OAuth onion, this next microservice, the `gateway`, is the outermost layer.
It is the first port-of-call for all requests destined for the microservices in our system.
When visitors to our site punch in the domain name for our system into a browser, it'll resolve to a loadbalancer serving this gateway service, and it is here where we'll originate an OAuth token.
This service is also a gateway, powered by Spring Cloud Gateway.
The gateway acts as a proxy, allowing us to forward requests to different hosts and ports, concealing from the user that the responses they're seeing are from different services.

The `gateway` service's job is entirely to handle the OAuth dance - if it detects that the request is not authenticated - and to otherwise proxy requests to two other HTTP endpoints: the `api` we just built, and have running on port `8081`, and the static HTML process running on port `8020`.

Here's the routing table

|===
|*HTTP origin*                                | *HTTP destination*
|http://gateway:8082/api/customers            | http://api:8080/customers
|http://gateway:8082/api/me                   | http://api:8080/me
|http://gateway:8082/api/email                | http://api:8080/email
|http://gateway:8082/index.html               | http://static:8020/index.html
|===

The `gateway` also sends along the JWT token to the downstream HTTP endpoints, acting as a token relay.
The `static` site won't care (it's just serving up static `.html` and `.css` files, after all), but the `api` is a resource server, and it will care.
The `api` will refuse to send back data unless that token is specified.

Let's look at the Java code first.

[source,java]
-----
include::gateway/src/main/java/bootiful/gateway/SecurityConfiguration.java[]
-----

<1> you could probably get away with not defining this bean at all _if_ you were willing to deal with default behavior of CSRF tokens, which I am not.
In the interest of simplicity, I'm disabling them, but in so doing I am also disabling all the other things Spring Security assumed I wanted.
So we will also go through and re-enable those things.
<2> We want all HTTP requests to be authenticated...
<3> ...and to disable the CSRF support...
<4> ...and to re-enable OAuth 2 OIDC login support and the OAuth 2 client support.
The OIDC login functionality is what triggers the OAuth dance we've talked about.
The OAuth 2 client support is what tells Spring Security, running in this process, as which OAuth 2 client requests for OIDC login should be done.
We'll need to specify the particulars in the property configuration later.

The security configuration is pretty straightforward.
We're an OAuth client.
We want to prompt users to login with a particular client.
Once a user is authenticated, well, there's not much for them to see!
We need Spring Cloud Gateway to connect our other HTTP services to the user visiting this `gateway` service.

We'll configure two Spring Cloud Gateway _routes_.
Each request has a predicate, optional filter(s), and a destination URI.
The predicate defines how requests to the Spring Cloud Gateway service are matched, e.g.: does this request have a particular header or cookie, or a particlar path, or a particular virtual host?
You may specify one or more filters that act on the incoming requests, changing it.
Finally, the request, after it has passed through any and all filters, is sent to a final destination, which we specify with a URI.

[source,java]
-----
include::gateway/src/main/java/bootiful/gateway/GatewayConfiguration.java[]
-----

<1> the first route matches all requests to `/api/**`, notes and forwards any OAuth JWTs to the backend service, and changes the path of the request from `gateway:8082/api/foo` to `api:8081/foo`, dropping the `/api/` bit.
<2> the second route takes every other request and sends it unchecked on to the HTTP endpoint service up the static HTMl 5 and JavaScript assets.

That's just about all the Java code for this service, but its role and importance in the architecture can not be overstated.
Let's look at the property file that ties it all together.

[source,properties]
-----
include::gateway/src/main/resources/application.properties[]
-----

<1> this process will run on port `8082`.
<2> it will use the issuer URI to validate JWTs if it detects them
<3> otherwise it will use this configuration to, acting as a client, inintiate an OIDC login to allow you to come up with a valid token.

The last several lines are where we tell the OAuth client what it should ask for from our OAuth IDP (the Spring Authorization Server).
You'd write similar configuration for any OAuth IDP, not just the Spring Authorization Server.
In this example, the client is configured to identify itself as the `crm` client, with `crm` as the client secret.
It's being configured to ask for the `authorization_code` authorization grant.
It's being configured to instruct the OAuth IDP to rediect _back_ to the gateway, with a special pseudo URL syntax: `{baseUrl}/login/oauth2/code/{registrationId}`.
Spring Security will set that endpoint up for us on the gateway, so there's nothing we need to do for that to work.
Finally, the OAuth client asks for certain permissions: `user.read` and `openid`.

== A User Interface for a Browser User

The OAuth client is where all outside visitors will begin their journey.
But obviously, they're not going to be issuing HTTP requests with `curl` , they're going to be expecting some sort of user interface.
We looked at how Spring Cloud Gateway requests will route proxied resources: `/api/**` to our backend `api` and everything else to the static HTML5 and JavaScript code.
In this case, it's just running on our local machines, but one images this stuff would be deployed to a CDN and made available locally in a real production application.

In order to keep things as simple as possible, I've written a snigle page `.html` application with a smattering - a pinch, a dash, even! - of JavaScript.
The concepts will be the same whether you eventually use Vue.js, React, Angular, jQuery, or whatever other thing you decide to use.

Here's the `.html` file.
It has a panel to greet the signed in user and another to show a grid of `customer` records.

[source,html]
----
include::static/index.html[]
----

Both the user name and the `customer` records we'll load by talking to the API from JavaScript.

[source,html]
----
include::static/app.js[]
----

<.> the first two functions of the file do the work of interacting with our API using the non-blocking, but oh-so-verbose, `async`/`await` syntax.
(If only JavaScript had Java 21's Project Loom and virtual threads!).
NB: we're making these requests relative to the `/api` path.
We've written the JavaScript code in such a way that it knows that it's being accessed via an HTTP proxy, our Spring Cloud Gateway gateway.
<.> this function is a little more interesting in that we're also interacting with the backend API but we're sending `POST` calls, not `GET` calls.
And of course we've got a little animation goin' on.
<.> there are at least two separate places that I need the `id` that'll have been assigned to a `div` for records for a particular `customer`.
So I've extracted it into a sepearate function here.
<.> this is the heart of the code: when the page loads, we read the data for the customers and the user's name and then draw the page with some DOM manipulation.
This code also wires up an event so that when you click on one of the rendered buttons, it triggers a `POST` which initiates a message sent to RabbitMQ.

I love this code, not because of the JavaScript (bleargh!), but because it's so plain to understand.
Remember, this code will run in a browser that has cookies associated with an HTTP session, and that HTTP session in turn is connected with a valid OAuth token.
So each time the JavaScript code calls `/api/customers`, it's implicitly sending the associated cookie to the gateway code, which in turn then allows the gateway to find the OAuth session associated with this user and to then forward the token to the backend `api`.

At no point does the JavaScript code ever see your username and password.
And, in this case, it doesn't even see your JWT!
The code is written in such a way that it doesn't even know OAuth is involved.
Now you can develop the application without OAuth, get it working, then add the OAuth resource server and OAuth client support to the backend code and call it done.

Remember, the user visiting the HTML page won't even see any of this markup unless they've authenticated.
They'll be redirected away before they ever get a chance.
This page is both completely and blissfully unaware of any security, and it doesn't need to be aware of security.

