==  Your First Cup of Java

Are you using the latest version of Java yet?
No?
That's a real pity, because it's basically a different language from the one you might've known.
This book was written with Java 21 in mind, but you should be using whatever the latest-and-greatest version of Java available to you is.

That said, i can appreciate that some of you may not have seen all that is new and nifty in the latest and greatest installments of Java, so we'll review some of my favorite features here.
If you're all caught up, then please move on to the next chapters - there's entirely too much to look at, anyway.

I don't know what the reason is, but I hope you're able to move up and over soon because Spring Framework 6 and Spring Boot 3 assume a Java 17 baseline.
That means that not only do those generations of Spring support Java 17 features (as did the Spring Framework 5 and Spring Boot generations), they also use some Java 17 features in their source code.
This book uses Spring Framework 6 and Spring Boot 3.

Whatever the cause of your hesitation, this chapter contains _spoilers_!
If you don't mind spoilers, let's dive right in!

First things first: you need an OpenJDK distribution that works for you.
The list of valid and viable distributions scrolls down to the floor and out the door, so I'll refer you to Fooojay.io's https://foojay.io/almanac/java-17/[handy version almanac for Java 17].
One of my favorite tools for managing my Java installations on UNIX-y type operating systems is https://sdkman.io/[`sdkman`].
It works on macOS, Windows Subsystem for Linux (WSL), Linux, and I'm sure other places besides.
I use the https://www.graalvm.org/[GraalVM] distribution.
GraalVM is an OpenJDK distribution with some extra features, including ahead-of-time native image compilation.
To get that distribution, you might say:

[source,shell]
----
sdk install java 21-graalce <1>
sdk default java 21-graalce <2>
----

<1> the first command installs the latest version of the GraalVM distribution of Java 21
<2> the second makes it the default installed distribution on my box so that all my interactions with Java are going to that distribution

With that done, let's look at some neat features in Java's latest and greatest versions up until Java 21.

=== Operations Improvements

The newer versions of Java now support something called CDS Archives.
CDS Archives essentially capture some of the invariant (but freshly computed) state from a given application and cache it for easy reuse on subsequent runs.
I consistently shave 0.1 or 0.2 seconds from startup time when using CDS Archives.

The newer versions of Java are also container aware.
So, let's suppose you are running Docker images on your host machine, which has 32GB of RAM.
You might configure the JRE with 2GB of RAM and errantly configure the Docker container with only 1GB of RAM.
Java would see the 32GB and think it could allocate 2GB and then fail to startup.
Java is aware of the container's limited RAM in newer versions and won't exceed it.

Java Flight Recorder (JEP 328) monitors and profiles running Java applications.
Even better, it does so with a low runtime footprint.
Java Mission Control allows ingesting and visualizing Java Flight Recorder data.
Java Mission Control takes Java's already stellar support for observability to the next level.

=== Performance

Java 21 is _fast_ and reliable.

Java's garbage collector is the stuff of legend.
It's fast, lightweight, and minimally invasive.
It's also one of those things where, when it's improved, your application's runtime improves with it, for free.
No recompilation is required.

G1 has been the default garbage collector since Java 9, replacing the Parallel garbage collector in Java 8. It reduces pause times with the default Parallel GC from Java 8, though it may have lower throughput overall.
Next, Java 11 introduced the ZGC garbage collector to reduce pauses further.
Finally, Java 14 introduced the Shenandoah GC, which keeps pause times low and does so in a manner independent of the heap's size.

And it's fast.
I can't give you a specific number or anything because it is so highly workload-sensitive, but https://www.optaplanner.org/blog/2021/09/15/HowMuchFasterIsJava17.html[this post from the folks at OptaPlanner] is persuasive.
They saw an average of 8.66% improvement for their CPU-intensive workloads when using the G1 GC, measured after a discarded 30 second warmup period.
These numbers reflect the jump from Java 11 (not Java 8) to Java 17. I can only imagine the numbers from Java 8 to Java 17 are even better. And the numbers for Java 21, even better still!
And that number is just an average: some workloads improved by as much as 23%!

=== Autocloseable

Java manages most memory for you, but it can't be responsible for the state outside of the humble confines of the JVM.
So, for example, you wouldn't like it if Java _garbage collected_ your connection to the database, and you wouldn't like it if Java garbage-collected your open socket connections without warning.
Therefore, the interfaces you use to interact with these external resources typically have a `close()` method that you, the client, need to call when working the external resource finishes.

You mustn't neglect to call that method!
Don't be greedy!
You're not greedy, are ya?
You want to leave the JVM as clean as you found it.
So, you write the boilerplate.
We all know the boilerplate: open the resource; work with it; surround that work with a `try`/`catch`/`finally` block; catch any `Throwable` instances if (_when_?) something goes wrong; `close()` the resource if something goes wrong.
Add the `close()` call in a `finally` block for extra robustness.
All the while, handle the exceptions that might arise when you try to do anything, including calling `close()` the resource.
You'll end up with one or more `try`/`catch` embedded within the outer `try`/`catch` blocks.

Let's look at some examples.
I'll read a file on the filesystem to demonstrate this new feature.
But something needs to ensure that there's a file to read in the first place, so I've extracted all that out into a separate class, `Utils`:

[source,java,indent=0]
----
include::java/src/test/java/bootiful/javareloaded/closeable/Utils.java[]
----

<1> the contents of the file, using a handy multiline Java `String`
<2> this method returns the `java.io.File` for the newly created temporary file
<3> a convenience method to log errors.
Do not rewrite this code!
Otherwise, if you're doing things the old-fashioned way, you'll find yourself rewriting this a _lot_.

Now, let's look at an example of what _not_ to do.

[source,java,indent=0]
----
include::java/src/test/java/bootiful/javareloaded/closeable/TraditionalResourceHandlingTest.java[]
----

<1>  from which file are we reading?
<2> We need a reference to the `BufferedReader` outside of the scope of the `try`/`catch` block, but we don't want to initialize that reference until we're inside the `try`/`catch` block because it might incur an exception.
<3> handle any errors.
Bear in mind that this solution doesn't even attempt to field the errors and somehow recover.
If there is _any_ error anywhere, then we abort.
<4> also, make sure to close that `Reader`!
Err, close that reader _if_ it's not `null`!
Sorry, close that reader _if_ it's not `null` and also don't forget to handle any errors in the doing, either!
Be kind, rewind!

Yuck.
We can do better with Java 7's `try-with-resources` construct.
Let's rework the example accordingly.

[source,java,indent=0]
----
include::java/src/test/java/bootiful/javareloaded/closeable/TryWithResourcesTest.java[]
----

=== Type Inference

Java 10 introduced type inference for variables given enough context.
As a result, Java is a strongly typed language with less typing - pressing of keys - required.

[source,java,indent=0]
----
include::java/src/test/java/bootiful/javareloaded/typeinference/TypeInferenceTest.java[]
----

<1> both variable definitions contain a type of `Customer`.
The compiler knows it, and you know it because the right side of the expression makes it clear.
So, all things being equal, why not use the more concise version?
<2> Indeed, in this case, the compiler knows _more_ about the type than it would before, particularly in the case of anonymous subclasses.
Suppose you need a throwaway object in which to stash some data temporarily?
If you created an anonymous subclass of `Object` and assigned it to a variable of type `Object`, there'd be no way to dereference fields defined on the anonymous subclass.
Traditionally, there was no way to reify _anonymous_ subclass types because they were _anonymous_.
But with `var`, you don't need to account for the type; you can let the compiler infer it.

This last bit - reifying anonymous subclasses comes in particularly handy when you're working with Java 8 streams abstractions and want to avoid having a host of throwaway classes created as side effects to conduct your data across the transformations.

The new `var` keyword can come in handy in a whole host of other smaller scenarios.
You can use the `var` keyword for parameters in a lambda definition.
It doesn't buy you much over just omitting `var` (or the type itself), except that you can now decorate the parameter with annotations.
Neat!

Lambdas are the one fly in the proverbial ointment, however.
Java doesn't have structural lambdas like Scala, Kotlin, and other languages.
Instead, you must assign the lambda to an instance of a functional interface like `java.util.function.Consumer<T>`.
If the literal lambda syntax doesn't clarify what type that is, then the variable type definition itself must.
So you can use `var` for every variable definition _except_ lambdas.
It's so dissatisfying!
The agony of having a column of nice, clean `var's punctuated occasionally with standard variable definitions just because those variables happen to be lambdas!
There is a way around it with casts, but I admit it isn't much better.
Let's look at some examples.

[source,java,indent=0]
----
include::java/src/test/java/bootiful/javareloaded/typeinference/LambdasAndTypeInferenceTest.java[]
----

<1> I can't use `var` here because the compiler doesn't know to which functional interface type the method reference, `delegate(String, Integer)`, should be assigned
<2> I can use `var` here, but I've lost all the brevity of lambdas!
<3> the only way I know around it is to cast the type like this.
Ugh.

I tend to use the cast form a lot.
Your sensibilities may vary, and given how new this feature is, I wouldn't be surprised if my sensibilities change in the future with respect to this feature, as well.

=== Enhanced Switch Expressions

Java has a new _enhanced_ switch, which forms the basis of the gradual addition of _pattern amtching_ to the Java language.
It simplifies things considerably:

[source,java,indent=0]
----
include::java/src/test/java/bootiful/javareloaded/switches/TraditionalSwitchExpressionTest.java[]
----

<1> `Emotion` is an `enum`.
There are only two possible values (for this simple example that doesn't at all reflect the rich gradient of human emotions) for a variable of type `Emotion`: `HAPPY` and `SAD`.
We have branches for all known states in this' switch' statement.
The compiler is satisfied that we have covered every possible value, so it doesn't insist on a `default` branch to handle any unforeseen values.
There are no unforeseen values.
We say that we've _exhausted_ the range of values.
<2> we define a variable to which we assign the results of our processing.
<3> take care to `break` for each branch.
Otherwise, the execution flow will drop down to other branches, producing undesirable side effects.

The first example is a classic `switch` statement.
There's nothing wrong, _per se_, but it's tedious, and I tend to avoid writing them.

[source,java,indent=0]
----
include::java/src/test/java/bootiful/javareloaded/switches/EnhancedSwitchExpressionTest.java[]
----

<1> there's no intermediate variable!
Each branch produces a value, and that value is the result of the `switch` expression and can be assigned to a variable or, as I do here, returned in one fell swoop from the method as any other expression would.

=== Multiline Strings

This one is a super-small feature that punches well above its weight: Java supports multiline `String`s: hooray!
There are a million opportunities for multiline `String`s: SQL queries, HTML, Markdown, Asciidoctor, Velocity templating (such as for emails), unit testing, etc.

[source,java,indent=0]
----
include::java/src/test/java/bootiful/javareloaded/MultilineStringsTest.java[]
----

<1> The first example uses a multiline `String` to represent some HTML markup
<2> The second variable recreates the same HTML markup, down to the padding and the newlines, but uses string concatenation and manually encodes newlines, as we used to have to do.

In the example, both variables `multilines`, and `concatenated`, are identical, but I the multiline `String` is much easier to wrangle.

Short and simple.

=== Records

Records are perhaps my second favorite new feature in Java.
If you've ever used case classes in Scala, or data classes in Kotlin, you'll feel _almost_ right at home.

Java introduced records, which are a new kind of type.
Records, like enums, are a restricted form of a class.
As a result, they're ideal for "plain data carriers," classes containing data not meant to be altered and only the most fundamental methods such as constructors and accessors.
We'll use (and sometimes abuse) them _all_ the time in this book.
They're wonderful time savers.
Need to model a read-only entity in your database that has accessors for all the constituent fields, a constructor, a functional `toString` implementation, a valid `equals` implementation, and a valid `hashCode` implementation?
You'd better get codin'!
That'll take a while.
Or, you could use something like Lombok to code-generate all of that for you based on the presence of a handful of annotations.
Or, you could use records.

Here's a trivial example.
Suppose you want to return information about `Customer` entities _and_ their associated `Order` data.
Unfortunately, Java doesn't support multiple return types or provide suitable tuple types, so you need to create something to hold both types.
Records to the rescue!

[source,java,indent=0]
----
include::java/src/test/java/bootiful/javareloaded/records/SimpleRecordsTest.java[]
----

<1> these three `record` definitions define three new types, each with accessors, constructors, and internal storage.
Scarcely more than three lines of code for three brand new types!
<2> records also automatically expose accessor methods for the fields defined in the constructor.
For example, if you want to read the `name` field of the `Customer` type, use `Customer#name()`.
If you wish to read the `orders` field of the `CustomerOrders` type, use `orders()`.
It took a while to accept that they they're in the form `x()`, and not in the form `getX()`, but I've come to love it.
Mercifully, all the interesting libraries that need to know about this convention - JSON serializers, for example - already work well with it.

Records make perfect sense for immutable, data-centric types.
They alleviate a whole host of boilerplate code.
In the first edition of this book, I used the https://projectlombok.org[Lombok project] (which is brilliant) to synthesize the getters, setters, no-args, and all-arg constructors with just a few annotations.
It worked, but it was still a handful of lines instead of the one-liners enabled by Java records.
I love records!

I still occasionally use Lombok for other things, but it's nice to reduce my reliance on it further.

More controversially, I also sometimes use records to implement services and components quickly.
After all, you can have methods on a record.
Of course, record implementations can't extend classes, but one doesn't need to do that a lot.
There is the undesirable side-effect of having accessor-methods that expose the state - `dataSource()` or whatever - but, for whatever reason, I don't care.
It doesn't cost me anything when I use it.
If my code grows large enough to need hierarchies or interface implementations, I'll change it.
If the code grows enough to worry about the leaking state, I'll change it.
But the immediate, short-term effect of having more concise, approachable, readable code seems to make sense to me.
Maybe one day that'll change?

Behind the scenes, a record creates a default constructor whose parameters match the types and rarity of the record header.
Records can have other constructors, but they need to delegate to the default constructor.

[source,java,indent=0]
----
include::java/src/test/java/bootiful/javareloaded/records/RecordConstructorsTest.java[]
----

<1> the default constructor is the one defined in the record header
<2> If you want to act on the fields passed in the default constructor, create a constructor with no parameters and do the work there.
This no-parameter constructor and the record header taken together are the default constructor.
If you want to have an alternative constructor, you can do that so long as you forward to the default constructor.
I use the default constructor to initialize the `id` to `-1`.
This way, it's impossible to initialize the record with a `null` `id` field.

=== Sealed Types

Sealed types are a novel feature that hasn't reached its full potential yet.
The basic idea is to constrain the number of subtypes for a given type.
Why would you do this?
Well, it's all a bit _exhausting_!
Or should I say, it's all about exhausting the extent to which the runtime needs to support virtual (polymorphic) dispatch?

Sound complicated?
It's not really.
Ever have a method in a parent type that the child type overrides?
The ability to call that method on an instance of that child type, in terms of the parent type's interface, is called polymorphism.

Polymorphic, or _virtual_, dispatch requires a lookup in the virtual function table, which in theory takes time.
The runtime wouldn't have to do that if it could say conclusively that a given type can never be subclassed, such as with a final type.
The `final` keyword is a bit of a sledgehammer, however.
It forecloses entirely on the possibility of on any kind whatsoever subclassing the final type.
You might have a hierarchy but wish to keep it shallow, and well-known.
Alternatively, you could make everything package-private (simply omit `public` modifier on the class), which means that only types in the same class could subclass the type.
This would probably work, but of course, somebody else could come along and create types in the same package in their `.jar`.
There's traditionally not been a lot of great ways to keep a hierarchy shallow until now.
Sealed types can help.
They let you constrain the number of subclasses to a known set.

Let's look at an example that is building out a

[source,java,indent=0]
----
include::java/src/test/java/bootiful/javareloaded/SealedTypesTest.java[]
----

<1>  we'll start with a `Shape` and permit two direct subclasses, `Oval` and `Polygon`.
<2> a subclass of a sealed type must be `final` or `sealed` and explicitly name its subclasses.
A sealed type's subclasses may themselves be sealed types, permitting further subtypes.
<3> the following declaration does not compile, as it is not one of the explicitly permitted subclasses
<4> the `describeShape` method is written so that we can exhaustively handle every subclass.

Sealed types help the compiler, too.
The compiler can exhaustively determine every case of every possible subtype, which has implications for the future, as Java looks to better incorporate simple pattern matching into Java.
Imagine the possibilities here, and you can kind of see how sealed types might play with the new `switch` expressions, too.

Right now, I don't recommend using `sealed` types.
I tend to think types should be open by default.
You just don't know what scenario will arise in the future that changes your fundamental assumptions.
Furthermore, sealed subtypes are `final`, inhibiting tools like Spring and Hibernate, which must subclass your types to proxy them.

=== Smart Casts

This feature is one of those things that I don't use all that often in application code, but it's pretty useful when writing infrastructure code when dealing with polymorphism.
Essentially, the feature spares you from having to create an intermediate variable and casting after you've already done an `instanceof` check.

[source,java,indent=0]
----
include::java/src/test/java/bootiful/javareloaded/SmartCastsTest.java[]
----

<1> this is a classic example, where we determine the subtype and then create a variable cast to the appropriate type.
If ever we change the type definition, we have to replace it both in the cast and in the `instanceof` check.
<2> the more excellent, newer alternative uses a smart-cast, sparing us the extra variable and cast.

This feature looks almost exactly like a similar feature in Kotlin, and I love it.

=== Function Interfaces, Lambdas  and Method References

Java 8 introduced lambdas.
They let us treat functions as first-class citizens that can be assigned and passed around.
Well, almost.
In Java, lambdas are slightly limited; they're _not_ first-class citizens.
But, close enough!
They _must_ have return values and input parameters compatible with the method signature of the sole abstract method of an interface.
This interface, one with a single abstract method intended for use as a lambda, is called a _functional interface_.
(Interfaces may also have _default_, non-abstract methods where the interface provides an implementation.)

There are some very convenient and oft-used functional interfaces in the JDK itself.
Here are some of my favorites.

* `java.util.function.Function<I, O>`: an instance of this interface accepts a type `I` and returns a type ` O'.
This is useful as a general-purpose function.
Every other function could, in theory, be generalized from this.
Thankfully, there's no need for that as several other handy functional interfaces exist.
* `java.util.function.Predicate<T>`: an instance of this interface accepts a type `T` and returns a `boolean`.
This is an ideal filter when you're trying to sift through a stream of values.
* `java.util.function.Supplier<T>`: A supplier accepts no input and returns an output.
* `java.util.function.Consumer<T>`: A consumer is the mirror image of a `Supplier<T>`; it takes an input and returns no output.

You can also create and use your custom functional interfaces.
Let's look at some examples.

[source,java,indent=0]
----
include::java/src/test/java/bootiful/javareloaded/LambdasTest.java[]
----

<1> You can use existing functional interfaces in the JDK...
<2> you can define your own interfaces and use them as functional interfaces
<3> You may use `var` and lambdas together with this (admittedly unsightly) cast.
<4> and if you have existing methods whose return types and input parameters line up with the single abstract method of a functional interface, then you can create a method reference and assign it to an instance of that type.

=== Pattern Matching

We've seen the smart casting `if` statement, and we've seen the switch expression.
At the heart of both of these new things is _pattern matching_, wherein we match a value and then extract the value for use.
We've only really seen that it's possible to easily match values thus far, so let's revisit that a bit.

[source,java]
----
include::java/src/test/java/bootiful/javareloaded/patternmatching/PatternMatchingTest.java[]
----

<.> for our examples, we're going to work with a shallow hierarchy rooted in a type called `BrowserClient`.
Imagine that when an HTTP request comes in, we adapt the request into one of either a known `Customer` or an `UnknownUser`.
<.> we'll do some analaysis of the incoming user type and display a message as appropriate.
Since we're going to prepare these same messages two different ways, I've extracted them out into separate environment variables.
<.> let's use the smart `if` statement to deduce which message to present.
Note that we're now switching on an instance of `BrowserClient`.
In the first line we do two things at once: we check that the variable is an instance of `Customer` and if so, we hoist out - we _extract_ not just the `Customer` variable, but instead the constituent component fields of the record itself - `id`, and `name` - into their own new variables.
Super concise.
In the second test, we don't need a pointer to the `UnknownUser` or its field, so we do nothing with it save match it.
<.> the if / else structure worked fine but it meant that we had to stash a variable and then make sure that only one branch of the test was ever evaluated.
The structure as written also gives us nothing in the way of comfort.
What happens when we add a new type to the hierarchy?
We need to handle that branch, but the compiler will let us ignore it.
Let's use our new friend the `switch` expression.
The switch expression has access to thes ame pattern matching super powers as the `if`, but it does us two new favors.
The compiler wwill complain if we add a new type to the hierarchy because it knows that the types are `sealed` and therefore there is an exhaustive set of types and our `switch` hasn't defined a `default` branch.
Thanks, compiler!
And, to make things jsut that much cleaner, the `switch` is an expression, so we can assign the results of the `switch` to a variable or just return the result of the expression directly.

I bet you never thought you'd see the day that the `switch` was more elegant than an `if`, did you?

Java language architect Brian Goetz talks about the combination of some of the features that we have just covered - pattern matching, sealed types, the smart switch expression - as  _data oriented programming_.
Java has reigned supreme in large monolithic codebases, he explains, because it provides good object-oriented support and strong enforcement of privacy, security and encapsulation.
In such a codebase, the boundary on which different parts of the program align is typically an object interface, which the magic of polymorphism incentivises.
But programs aren't usually large, sprawling, deeply rooted graphs of objects these days.
More often than not they're smaller programs dealing with ad-hoc messages coming in over the wire and being handled in terms of dumb, but typed, carriers.
There's no hierarchy at all!
In this context, Java 8 was starting to feel mighty clunky.
But no more.
With Java 21, it's trivial to define small ad-hoc objects and to vary behavior based on those objects.
In a sense, Java 21 introduces a new kind of dispatch: not the dynamic dispatch of yore, but a dispatch for small ad-hoc objects.

And just like that, without us ever realizing it, Java 21 manages to introduce support for a completely new style of programming: data oriented programming.
And I bet you were only just getting used to the possibilities of the rudimentary functional programming support in Java 8!

=== Java 21, Project Loom, and Virtual Threads

Project Loom brings transparent fibers to the JVM.
As things stand today, in Java 20 or earlier, IO is blocking.
Call `int InputStream#read()`, and you might have to wait for the next byte to finally arrive.
In `java.io.File`-centric IO, there's very rarely much of a delay.
On the network, however, you just can't really ever know.
Clients might disconnect.
Clients be people, driving through a tunnel and getting spotty signal coverage.
During this time, the program flow is said to be _blocked_ from proceeding on the thread of execution.
In the following snippet, we have no way of knowing when we'll see the word "after" printed.
Might be a nanosecond from now.
Might be a week from now.
It's _blocking_.

[source,java]
----
include::java/snippets/traditional-io[]
----

This means that we can't address any other requests with this thread until it's finished doing whatever it was doing.
We'll need more threads.

This is bad enough, but it's made worse by the architecture of threading in Java prior to Java 21 where each thread maps, more or less, to a native operating system thread.
It's expensive to create more threads, too, taking about two megabytes of RAM.
We're going to need a _lot_ of threads to handle requests if our existing threads are blocked long enough.
Many, many, times more threads.
Or, we're going to need to find a way to avoid _blocking_ on the precious few threads we do have.

We could use non-blocking IO, as enabled by Java NIO (java.nio.\*).
In this model, you ask for bytes and register a callback that the runtime executes only when there are actually bytes available.
No waiting, no blocking.
This approach has the significant benefit of keeping us off threads when there's nothing to be done, allowing others to use those threads in the meantime.
It's a bit tedious, however, and low-level.
Spring has amazing support for reactive programming, which offers a functional-style programming model on top of non-blocking IO.
It works well.
But, it requires changing the way you write code.
If you're not used to it, it can be a bit daunting, too.
Wouldn't it be nice if you could just take that existing code, as demonstrated above, and have it do the right thing, transparently moving the flow of execution off the thread when there's nothing happening, and then resuming the flow of execution when there is?
This way, we could keep our relatively simpler code, and get the benefits of non-blocking IO.
Absolutely it would.
And now you can.
Project Loom is straightforward at the high levels: if you run your code in a _virtual thread_ (just another type of `java.lang.Thread`), then the runtime will detect _blocking_ operations like `InputStream#read()`, `Thread.sleep(long)`, etc., and automatically move the code off the thread its on if it's in a state where nothing is happening.
It'll move the code back on to the thread once there's something to be, once the blocking operation has stopped blocking.
In the case of reading, that means it'll resume once there are bytes to read.
In the case of `Thread.sleep`, it'll resume once the sleep time has elapsed.
And you don't have to do anything to get it to work.
Let's look at an example that I shamelessly stole from Oracle Java advocate José Paumard.

[source,java]
----
include::java/src/test/java/bootiful/javareloaded/loom/LoomTest.java[]
----

<.> This program launches a 1000 virtual threads.
This is an arbitrary number, but it's also enough that it'll create contention - a need to share the precious few resources available to the machine.
<.> the program sleeps five times in each thread, for about 100 milliseconds each.
This is not a long time, but it's enough that it forces the runtime to have to interleave, to _share_, the actual operating system threads.
<.> In each thread we call the `observe` function, which notes the current thread, sleeps, and then notes the current thread again.
We don't want all the threads, however, as that would be too many.
So we sample: if we're on the first thread (whose index would be `0`) launched, not the information; otherwise: do nothing with the information and move on.
<.> by the end of the run, we've captured the thread on which our first of a thousand threads executed and stored them in a `Set<String>`, where the values will be deduplicated.
Interestingly, there is _probably_ more than one value in the set!
Remember, we only noted the thread of execution for _one_ thread - the _same_ thread! - and somehow - without us asking or doing anything, it got moved around.
Print the values out, and you'll see the code ran on the same  _virtual_ thread, but on multiple carrier threads.

The result is that while we were `Thread.sleep`-ing, the carrier thread on which we were executing was made available to whatever else required it in the JVM.
This efficient time-sharing means that now we can handle a _lot_ more requests with the same codebase.
All we had to do was make sure to run the code on a _virtual_ thread.

You don't have to use the `Thread.ofVirtual()` construction, either.
There's an `Executor` implementation, too: `Executors.newVirtualThreadPerTaskExecutor()`.
It's not a pool, however.
Threads are no longer expensive, after all.

That's easy enough.
In a typical Spring Boot application, however, there are countless places where you'll need to override the default configured `Executor`, but in Spring Boot 3.2 we can do that for you.
Specify `spring.threads.virtual.enabled=true` and you're all set.

Loom is especially important in the context of the Spring Authorization Server, because it uses traditional blocking IO.
If you want to easily scale it up, consider using virtual threads and Java 21 when running the Spring Authorization Server.
Who knows, you may not need to add new instances.
You'll get to have your cake and eat it too: scalable, but simpler, code.

=== Next Steps

I didn't intend for this chapter to be a thorough introduction to all things Java.
Just an amuse-bouche for all the cool stuff you might see me do in my code independent of Spring.
Java 21 is a very compelling way to write code, and it's no coincidence that it's starting to look more and more like languages like Kotlin, which is also a lovely way to write Spring Boot-based applications.
Hopefully, this chapter has been persuasive, and you're ready to turn the page.